"""Constants relating to MIDI files in general and music theory."""


from . import Chord


__all__ = ['SCALES', 'CHORDS', 'PROGRESSIONS', 'BASELINES', 'INSTRUMENTS',
           'PERCUSSION', 'PITCH_LOOKUP']


SCALES = {
    'chromatic': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
    'major': [2, 2, 1, 2, 2, 2, 1],
    'harmonic_minor': [2, 1, 2, 2, 1, 3, 1],
    'minor_pentatonic': [3, 2, 2, 3, 2],
    'natural_minor': [2, 1, 2, 2, 1, 2, 2],
    'melodic_minor_up': [2, 1, 2, 2, 2, 2, 1],
    'melodic_minor_down': [2, 2, 1, 2, 2, 1, 2],
    'dorian': [2, 1, 2, 2, 2, 1, 2],
    'mixolydian': [2, 2, 1, 2, 2, 1, 2],
    'ahava_raba': [1, 3, 1, 2, 1, 2, 2],
    'major_pentatonic': [2, 2, 3, 2, 3],
    'diatonic': [2, 2, 2, 2, 2, 2],
    'dim': [1, 2, 1, 2, 1, 2, 1, 2]
}
"""A list of common scales represented as half-steps between notes."""


CHORDS = {
    'major': [0, 4, 7],
    'minor': [0, 3, 7],
    'major7': [0, 4, 7, -1],
    'dom7': [0, 4, 7, -2],
    'minor7': [0, 3, 7, -2],
    'dim': [0, 3, 6],
    'fdim': [0, 3, 6, 9],
    'n': [0],
    'dom7-5': [0, 4, 7, 9, -5],
    'dom7-3': [0, 4, 7, 9, -8],
    'minor3': [0, 3, 7, -8]
}
"""A list of common chords represented as half-steps between notes."""


PROGRESSIONS = {
    'I-vi-IV-V': ([
        Chord(CHORDS['major'], SCALES['major'], 0),
        Chord(CHORDS['minor'], SCALES['harmonic_minor'], 9),
        Chord(CHORDS['major'], SCALES['major'], 5),
        Chord(CHORDS['major'], SCALES['major'], 7),
    ], 'major'),
    'ii-V7-I': ([
        Chord(CHORDS['minor'], SCALES['harmonic_minor'], 2),
        Chord(CHORDS['dom7'], SCALES['major'], 7),
        Chord(CHORDS['major'], SCALES['major'], 0),
    ], 'major'),
    # 'iv-III-bII-I': ([
    #     Chord(CHORDS['minor'], SCALES['harmonic_minor'], 5),
    #     Chord(CHORDS['major'], SCALES['major'], 4),
    #     Chord(CHORDS['major'], SCALES['major'], 3),
    #     Chord(CHORDS['major'], SCALES['major'], 0),
    # ], 'major'),
    'I-V-bVII-IV': ([
        Chord(CHORDS['major'], SCALES['major'], 0),
        Chord(CHORDS['major'], SCALES['major'], 7),
        Chord(CHORDS['major'], SCALES['major'], 10),
        Chord(CHORDS['major'], SCALES['major'], 5),
    ], 'major'),
    'vi-ii-V-I': ([
        Chord(CHORDS['minor'], SCALES['harmonic_minor'], 9),
        Chord(CHORDS['minor'], SCALES['harmonic_minor'], 2),
        Chord(CHORDS['major'], SCALES['major'], 7),
        Chord(CHORDS['major'], SCALES['major'], 0),
    ], 'major'),
    'I-IV-ii-V': ([
        Chord(CHORDS['major'], SCALES['major'], 0),
        Chord(CHORDS['major'], SCALES['major'], 5),
        Chord(CHORDS['major'], SCALES['harmonic_minor'], 2),
        Chord(CHORDS['major'], SCALES['major'], 7),
    ], 'major'),
    'I-V-vi-iii-IV-I-IV-V': ([
        Chord(CHORDS['major'], SCALES['major'], 0),
        Chord(CHORDS['major'], SCALES['major'], 7),
        Chord(CHORDS['minor'], SCALES['harmonic_minor'], 9),
        Chord(CHORDS['minor'], SCALES['harmonic_minor'], 4),
        Chord(CHORDS['major'], SCALES['major'], 5),
        Chord(CHORDS['major'], SCALES['major'], 0),
        Chord(CHORDS['major'], SCALES['major'], 5),
        Chord(CHORDS['major'], SCALES['major'], 7),
    ], 'major'),
    'i-VII-i-V-III-VII-i-V-i': ([
        Chord(CHORDS['minor'], SCALES['harmonic_minor'], 0),
        Chord(CHORDS['major'], SCALES['major'], 10),
        Chord(CHORDS['minor'], SCALES['harmonic_minor'], 0),
        Chord(CHORDS['major'], SCALES['major'], 7),
        Chord(CHORDS['major'], SCALES['major'], 3),
        Chord(CHORDS['major'], SCALES['major'], 10),
        Chord(CHORDS['minor'], SCALES['harmonic_minor'], 0),
        Chord(CHORDS['major'], SCALES['major'], 7),
        Chord(CHORDS['minor'], SCALES['harmonic_minor'], 0),
    ], 'minor'),
    'hungarian': ([
        Chord(CHORDS['minor'], SCALES['harmonic_minor'], 0),
        Chord(CHORDS['minor'], SCALES['harmonic_minor'], 7),
        Chord(CHORDS['minor'], SCALES['harmonic_minor'], 0),
        Chord(CHORDS['minor'], SCALES['harmonic_minor'], 7),
        Chord(CHORDS['minor'], SCALES['harmonic_minor'], 2),
        Chord(CHORDS['minor'], SCALES['harmonic_minor'], 7),
        Chord(CHORDS['minor'], SCALES['harmonic_minor'], 0),
        Chord(CHORDS['minor'], SCALES['harmonic_minor'], 7),
    ], 'minor'),
    'simple_m': ([
        Chord(CHORDS['minor'], SCALES['harmonic_minor'], 0),
        Chord(CHORDS['minor'], SCALES['harmonic_minor'], 5),
        Chord(CHORDS['minor'], SCALES['harmonic_minor'], 0),
        Chord(CHORDS['minor'], SCALES['harmonic_minor'], 7),
    ], 'minor'),
    'simple_M': ([
        Chord(CHORDS['major'], SCALES['major'], 0),
        Chord(CHORDS['major'], SCALES['major'], 5),
        Chord(CHORDS['major'], SCALES['major'], 0),
        Chord(CHORDS['major'], SCALES['major'], 7),
    ], 'major'),
    'creepy1_m': ([
        Chord(CHORDS['minor'], SCALES['harmonic_minor'], 0),
        Chord(CHORDS['major'], SCALES['major'], 8),
        Chord(CHORDS['minor'], SCALES['harmonic_minor'], 5),
        Chord(CHORDS['minor'], SCALES['harmonic_minor'], 7),
    ], 'minor'),
    'creepy2_m': ([
        Chord(CHORDS['minor'], SCALES['harmonic_minor'], 0),
        Chord(CHORDS['major'], SCALES['major'], 8),
        Chord(CHORDS['fdim'], SCALES['dim'], 2),
        Chord(CHORDS['minor'], SCALES['harmonic_minor'], 7),
    ], 'minor'),
    'cliche1_m': ([
        Chord(CHORDS['minor'], SCALES['harmonic_minor'], 0),
        Chord(CHORDS['minor'], SCALES['harmonic_minor'], 7),
        Chord(CHORDS['major'], SCALES['major'], 8),
        Chord(CHORDS['minor'], SCALES['harmonic_minor'], 5),
    ], 'minor'),
    'cliche1_M': ([
        Chord(CHORDS['major'], SCALES['major'], 0),
        Chord(CHORDS['major'], SCALES['major'], 7),
        Chord(CHORDS['minor'], SCALES['harmonic_minor'], 9),
        Chord(CHORDS['major'], SCALES['major'], 5),
    ], 'major'),
    'cliche2_m': ([
        Chord(CHORDS['minor'], SCALES['harmonic_minor'], 0),
        Chord(CHORDS['major'], SCALES['major'], 8),
        Chord(CHORDS['major'], SCALES['major'], 3),
        Chord(CHORDS['major'], SCALES['major'], 10),
    ], 'minor'),
    'rebellious_m': ([
        Chord(CHORDS['minor'], SCALES['harmonic_minor'], 5),
        Chord(CHORDS['minor'], SCALES['harmonic_minor'], 0),
        Chord(CHORDS['minor'], SCALES['harmonic_minor'], 5),
        Chord(CHORDS['minor'], SCALES['harmonic_minor'], 7),
    ], 'minor'),
    'rebellious_M': ([
        Chord(CHORDS['major'], SCALES['major'], 5),
        Chord(CHORDS['major'], SCALES['major'], 0),
        Chord(CHORDS['major'], SCALES['major'], 5),
        Chord(CHORDS['major'], SCALES['major'], 7),
    ], 'major'),
    'memories_m': ([
        Chord(CHORDS['minor'], SCALES['harmonic_minor'], 0),
        Chord(CHORDS['minor'], SCALES['harmonic_minor'], 5),
        Chord(CHORDS['minor'], SCALES['harmonic_minor'], 0),
        Chord(CHORDS['minor'], SCALES['harmonic_minor'], 7),
    ], 'minor'),
    'memories_M': ([
        Chord(CHORDS['major'], SCALES['major'], 0),
        Chord(CHORDS['major'], SCALES['major'], 5),
        Chord(CHORDS['major'], SCALES['major'], 0),
        Chord(CHORDS['major'], SCALES['major'], 7),
    ], 'major'),
    'sad_m': ([
        Chord(CHORDS['minor'], SCALES['harmonic_minor'], 0),
        Chord(CHORDS['minor'], SCALES['harmonic_minor'], 5),
        Chord(CHORDS['minor'], SCALES['harmonic_minor'], 7),
        Chord(CHORDS['minor'], SCALES['harmonic_minor'], 7),
    ], 'minor'),
    'sad_M': ([
        Chord(CHORDS['major'], SCALES['major'], 0),
        Chord(CHORDS['major'], SCALES['major'], 5),
        Chord(CHORDS['major'], SCALES['major'], 7),
        Chord(CHORDS['major'], SCALES['major'], 7),
    ], 'major'),
    'alternative_m': ([
        Chord(CHORDS['major'], SCALES['major'], 8),
        Chord(CHORDS['minor'], SCALES['harmonic_minor'], 5),
        Chord(CHORDS['minor'], SCALES['harmonic_minor'], 0),
        Chord(CHORDS['minor'], SCALES['harmonic_minor'], 7),
    ], 'minor'),
    'alternative_M': ([
        Chord(CHORDS['minor'], SCALES['harmonic_minor'], 9),
        Chord(CHORDS['major'], SCALES['major'], 5),
        Chord(CHORDS['major'], SCALES['major'], 0),
        Chord(CHORDS['major'], SCALES['major'], 7),
    ], 'major'),
}
"""A list of common chord progressions."""


BASELINES = {
    'block': ([
        (0, 0),
        (1, 0),
        (2, 0),
        ], -1, 0),
    'mega-block': ([
        (0, 0),
        (1, 0),
        (2, 0),
        (3, 0),
        (4, 0),
        ], -1, -1),
    'walk': ([
        (0, 0),
        (1, 1),
        (2, 2),
        (3, 3),
        ], 1, 0),
    'staccato-walk': ([
        (0, 0),
        (1, 1),
        (2, 2),
        (3, 3),
        ], 0.25, 0),
    'legato-scale': ([
        (0, 0),
        (1, 0.5),
        (2, 1),
        (3, 1.5),
        (4, 2),
        (3, 2.5),
        (2, 3),
        (1, 3.5),
        ], 1, -1),
    'staccato-scale': ([
        (0, 0),
        (1, 0.5),
        (2, 1),
        (3, 1.5),
        (4, 2),
        (3, 2.5),
        (2, 3),
        (1, 3.5),
        ], 0.25, -1),
    'legato-russian': ([
        (0, 0),
        (1, 1), (2, 1),
        (-2, 2),
        (1, 3), (2, 3),
        ], 0.75, 0),
    'staccato-russian': ([
        (0, 0),
        (1, 1), (2, 1),
        (-2, 2),
        (1, 3), (2, 3),
        ], 0.25, 0),
    'moonlight': ([
        (0, 0), (2, 0.5), (1, 1), (2, 1.5),
        (0, 2), (2, 2.5), (1, 3), (2, 3.5),
        ], 1, 0),
}
"""A list of common baselines. Contains a list of tuples with the 
format chord_position, time. A note length, octave offset is also 
included with each baseline. A negative note length indicates a length 
for the entire measure.
"""


INSTRUMENTS = {
    'Acoustic Grand Piano': 0,
    'Bright Acoustic Piano': 1,
    'Electric Grand Piano': 2,
    'Honky-tonk Piano': 3,
    'Electric Piano 1': 4,
    'Electric Piano 2': 5,
    'Harpsichord': 6,
    'Clavi': 7,
    'Celesta': 8,
    'Glockenspiel': 9,
    'Music Box': 10,
    'Vibraphone': 11,
    'Marimba': 12,
    'Xylophone': 13,
    'Tubular Bells': 14,
    'Dulcimer': 15,
    'Drawbar Organ': 16,
    'Percussive Organ': 17,
    'Rock Organ': 18,
    'Church Organ': 19,
    'Reed Organ': 20,
    'Accordion': 21,
    'Harmonica': 22,
    'Tango Accordion': 23,
    'Acoustic Guitar (nylon)': 24,
    'Acoustic Guitar (steel)': 25,
    'Electric Guitar (jazz)': 26,
    'Electric Guitar (clean)': 27,
    'Electric Guitar (muted)': 28,
    'Overdriven Guitar': 29,
    'Distortion Guitar': 30,
    'Guitar harmonics': 31,
    'Acoustic Bass': 32,
    'Electric Bass (finger)': 33,
    'Electric Bass (pick)': 34,
    'Fretless Bass': 35,
    'Slap Bass 1': 36,
    'Slap Bass 2': 37,
    'Synth Bass 1': 38,
    'Synth Bass 2': 39,
    'Violin': 40,
    'Viola': 41,
    'Cello': 42,
    'Contrabass': 43,
    'Tremolo Strings': 44,
    'Pizzicato Strings': 45,
    'Orchestral Harp': 46,
    'Timpani': 47,
    'String Ensemble 1': 48,
    'String Ensemble 2': 49,
    'SynthStrings 1': 50,
    'SynthStrings 2': 51,
    'Choir Aahs': 52,
    'Voice Oohs': 53,
    'Synth Voice': 54,
    'Orchestra Hit': 55,
    'Trumpet': 56,
    'Trombone': 57,
    'Tuba': 58,
    'Muted Trumpet': 59,
    'French Horn': 60,
    'Brass Section': 61,
    'SynthBrass 1': 62,
    'SynthBrass 2': 63,
    'Soprano Sax': 64,
    'Alto Sax': 65,
    'Tenor Sax': 66,
    'Baritone Sax': 67,
    'Oboe': 68,
    'English Horn': 69,
    'Bassoon': 70,
    'Clarinet': 71,
    'Piccolo': 72,
    'Flute': 73,
    'Recorder': 74,
    'Pan Flute': 75,
    'Blown Bottle': 76,
    'Shakuhachi': 77,
    'Whistle': 78,
    'Ocarina': 79,
    'Lead 1 (square)': 80,
    'Lead 2 (sawtooth)': 81,
    'Lead 3 (calliope)': 82,
    'Lead 4 (chiff)': 83,
    'Lead 5 (charang)': 84,
    'Lead 6 (voice)': 85,
    'Lead 7 (fifths)': 86,
    'Lead 8 (bass + lead)': 87,
    'Pad 1 (new age)': 88,
    'Pad 2 (warm)': 89,
    'Pad 3 (polysynth)': 90,
    'Pad 4 (choir)': 91,
    'Pad 5 (bowed)': 92,
    'Pad 6 (metallic)': 93,
    'Pad 7 (halo)': 94,
    'Pad 8 (sweep)': 95,
    'FX 1 (rain)': 96,
    'FX 2 (soundtrack)': 97,
    'FX 3 (crystal)': 98,
    'FX 4 (atmosphere)': 99,
    'FX 5 (brightness)': 100,
    'FX 6 (goblins)': 101,
    'FX 7 (echoes)': 102,
    'FX 8 (sci-fi)': 103,
    'Sitar': 104,
    'Banjo': 105,
    'Shamisen': 106,
    'Koto': 107,
    'Kalimba': 108,
    'Bag pipe': 109,
    'Fiddle': 110,
    'Shanai': 111,
    'Tinkle Bell': 112,
    'Agogo': 113,
    'Steel Drums': 114,
    'Woodblock': 115,
    'Taiko Drum': 116,
    'Melodic Tom': 117,
    'Synth Drum': 118,
    'Reverse Cymbal': 119,
    'Guitar Fret Noise': 120,
    'Breath Noise': 121,
    'Seashore': 122,
    'Bird Tweet': 123,
    'Telephone Ring': 124,
    'Helicopter': 125,
    'Applause': 126,
    'Gunshot': 127,
}
"""List of MIDI general-1 instruments and their corresponding codes."""


PERCUSSION = {
    'Acoustic Bass Drum': 34,
    'Bass Drum 1': 35,
    'Side Stick': 36,
    'Acoustic Snare': 37,
    'Hand Clap': 38,
    'Electric Snare': 39,
    'Low Floor Tom': 40,
    'Closed Hi Hat': 41,
    'High Floor Tom': 42,
    'Pedal Hi-Hat': 43,
    'Low Tom': 44,
    'Open Hi-Hat': 45,
    'Low-Mid Tom': 46,
    'Hi-Mid Tom': 47,
    'Crash Cymbal 1': 48,
    'High Tom': 49,
    'Ride Cymbal 1': 50,
    'Chinese Cymbal': 51,
    'Ride Bell': 52,
    'Tambourine': 53,
    'Splash Cymbal': 54,
    'Cowbell': 55,
    'Crash Cymbal 2': 56,
    'Vibraslap': 57,
    'Ride Cymbal 2': 58,
    'Hi Bongo': 59,
    'Low Bongo': 60,
    'Mute Hi Conga': 61,
    'Open Hi Conga': 62,
    'Low Conga': 63,
    'High Timbale': 64,
    'Low Timbale': 65,
    'High Agogo': 66,
    'Low Agogo': 67,
    'Cabasa': 68,
    'Maracas': 69,
    'Short Whistle': 70,
    'Long Whistle': 71,
    'Short Guiro': 72,
    'Long Guiro': 73,
    'Claves': 74,
    'Hi Wood Block': 75,
    'Low Wood Block': 76,
    'Mute Cuica': 77,
    'Open Cuica': 78,
    'Mute Triangle': 79,
    'Open Triangle': 80,
}
"""List of MIDI general-1 percussion instruments and their corresponding codes.
To use, add a note to channel 9 with the pitch being the desired instrument."""


PITCH_LOOKUP = {
    12: 'C0',
    13: 'C#0',
    14: 'D0',
    15: 'D#0',
    16: 'E0',
    17: 'F0',
    18: 'F#0',
    19: 'G0',
    20: 'G#0',
    21: 'A0',
    22: 'A#0',
    23: 'B0',
    24: 'C1',
    25: 'C#1',
    26: 'D1',
    27: 'D#1',
    28: 'E1',
    29: 'F1',
    30: 'F#1',
    31: 'G1',
    32: 'G#1',
    33: 'A1',
    34: 'A#1',
    35: 'B1',
    36: 'C2',
    37: 'C#2',
    38: 'D2',
    39: 'D#2',
    40: 'E2',
    41: 'F2',
    42: 'F#2',
    43: 'G2',
    44: 'G#2',
    45: 'A2',
    46: 'A#2',
    47: 'B2',
    48: 'C3',
    49: 'C#3',
    50: 'D3',
    51: 'D#3',
    52: 'E3',
    53: 'F3',
    54: 'F#3',
    55: 'G3',
    56: 'G#3',
    57: 'A3',
    58: 'A#3',
    59: 'B3',
    60: 'C4',
    61: 'C#4',
    62: 'D4',
    63: 'D#4',
    64: 'E4',
    65: 'F4',
    66: 'F#4',
    67: 'G4',
    68: 'G#4',
    69: 'A4',
    70: 'A#4',
    71: 'B4',
    72: 'C5',
    73: 'C#5',
    74: 'D5',
    75: 'D#5',
    76: 'E5',
    77: 'F5',
    78: 'F#5',
    79: 'G5',
    80: 'G#5',
    81: 'A5',
    82: 'A#5',
    83: 'B5',
    84: 'C6',
    85: 'C#6',
    86: 'D6',
    87: 'D#6',
    88: 'E6',
    89: 'F6',
    90: 'F#6',
    91: 'G6',
    92: 'G#6',
    93: 'A6',
    94: 'A#6',
    95: 'B6',
    96: 'C7',
    97: 'C#7',
    98: 'D7',
    99: 'D#7',
    100: 'E7',
    101: 'F7',
    102: 'F#7',
    103: 'G7',
    104: 'G#7',
    105: 'A7',
    106: 'A#7',
    107: 'B7',
    108: 'C8',
    109: 'C#8',
    110: 'D8',
    111: 'D#8',
    112: 'E8',
    113: 'F8',
    114: 'F#8',
    115: 'G8',
    116: 'G#8',
    117: 'A8',
    118: 'A#8',
    119: 'B8',
    120: 'C9',
    121: 'C#9',
    122: 'D9',
    123: 'D#9',
    124: 'E9',
    125: 'F9',
    126: 'F#9',
    127: 'G9',
}
"""A lookup table for MIDI pitches and the corresponding English name."""
