"""Views, one for each Insta485 page."""
from insta485.views.index import show_index
from insta485.views.users import show_user
from insta485.views.users import show_followers
from insta485.views.users import show_following
from insta485.views.users import following
from insta485.views.posts import show_post
from insta485.views.posts import post
from insta485.views.likes import likes
from insta485.views.helpers import download_file
from insta485.views.explore import show_explore
from insta485.views.accounts import show_login
from insta485.views.accounts import logout
from insta485.views.accounts import show_create
from insta485.views.accounts import show_delete
from insta485.views.accounts import show_edit
from insta485.views.accounts import show_password
from insta485.views.accounts import auth
from insta485.views.accounts import account
from insta485.views.comments import comments
